CREATE DATABASE contacts;
USE DATABASE contacts;

DROP TABLE IF EXISTS contact;

CREATE TABLE contact(
   CONTACT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   NICKNAME VARCHAR(20),
   ADDRESS VARCHAR(128),
   CELLPHONE_NUMBER VARCHAR(10),
   EMAIL VARCHAR(10),
   WEBSITE VARCHAR(10),
   PROFESSION VARCHAR(100),
   BIRTH_DATE VARCHAR(100),
   PRIMARY KEY (CONTACT_ID)
);

INSERT INTO contact (NAME, NICKNAME, ADDRESS, CELLPHONE_NUMBER,
   EMAIL, BIRTH_DATE, WEBSITE,PROFESSION)
   VALUES ('Bruce Wayne', 'batman', 'XYZ Batcave', '9876543210',
   'batman@gmail.com','1976/02/03', 'batblog.com', 'Super Hero');
